{% set build = 0 %}
{% set version = "2020.10.02" %}

package:
  name: channel-helper
  version: {{ version }}

source:
  git_url: https://gist.github.com/milljm/8e0f6f995e6b9b638e0168797814471f.git
  git_branch: master

build:
  number: {{ build }}  # [linux,osx]
  skip: true           # [win]

requirements:
  build:
    - requests
  run:
    - requests

test:
  imports:
    - channel_helper
  commands:
    - channel_helper --help

about:
  home: https://github.com/milljm/channel_helper
  license: LGPL 2.1
  summary: 'HIT Parser'

extra:
  recipe-maintainers:
    - milljm
